# Peter Shin (G01073633)
# Deployment yaml configuration for kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645-hw3
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hw3
  template:
    metadata:
      labels:
        run: hw3
    spec:
      containers:
      - name: hw2-container
        image: frozenmandu/hw3-frontend:5
        imagePullPolicy: Always
        ports:
        - containerPort: 80